disabled_rules: # 실행에서 제외할 룰 식별자들
  - control_statement
  # 테스트 하기 위해 콤마 일부러 제외
opt_in_rules: # 일부 룰은 옵트 인 형태로 제공
  - empty_count
  - force_unwrapping
  # 사용 가능한 모든 룰은 swiftlint rules 명령으로 확인 가능
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
  - TestSwiftLint

excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - TestSwiftLint/AppDelegate.swift
  - TestSwiftLint/SceneDelegate.swift

# 설정 가능한 룰은 이 설정 파일에서 커스터마이징 가능
# 경고나 에러 중 하나를 발생시키는 룰은 위반 수준을 설정 가능
force_cast: error # 암시적으로 지정
force_try:
  severity: warning
line_length: 139
# 값을 나열해서 암시적으로 양쪽 다 지정할 수 있음
type_body_length:
  - 300 # 경고
  - 400 # 에러
# 둘 다 명시적으로 지정할 수도 있음
file_length:
  warning: 500
  error: 1200
# https://realm.github.io/SwiftLint/rule-directory.html 더 많은 룰 찾아보기
